// Centralized component styles for ROCA App
// All theme-aware styles in one place

// PropertyCard styles
export const getPropertyCardStyles = (t) => ({
  card: {
    background: t.colors.bgCard,
    borderRadius: 16,
    border: `1px solid ${t.colors.border}`,
    position: "relative",
    transition: "all 0.2s ease",
    cursor: "pointer",
  },
  cardMain: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    padding: 16,
    gap: 12,
  },
  cardLeft: {
    flex: 1,
    minWidth: 0,
  },
  cardName: {
    fontWeight: 700,
    fontSize: 15,
    color: t.colors.text,
    marginBottom: 4,
  },
  cardSub: {
    fontSize: 12,
    color: t.colors.textMuted,
    marginBottom: 4,
  },
  cardPrice: {
    fontWeight: 700,
    fontSize: 14,
    color: t.colors.primary,
  },
  cardRight: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    position: "relative",
  },
  statusBadge: (ec) => ({
    fontSize: 11,
    fontWeight: 700,
    borderRadius: 20,
    padding: "4px 10px",
    display: "flex",
    alignItems: "center",
    whiteSpace: "nowrap",
    backgroundColor: ec?.bg || t.colors.success,
    color: t.colors.text,
  }),
  statusDot: (ec) => ({
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: ec?.dot || t.colors.text,
    display: "inline-block",
    marginRight: 4,
  }),
  dropdown: {
    background: t.colors.bgCard,
    borderRadius: 12,
    padding: 8,
    boxShadow: "0 8px 32px rgba(0,0,0,0.5)",
    position: "absolute",
    right: "100%",
    marginRight: 8,
    top: "50%",
    transform: "translateY(-50%)",
    zIndex: 50,
    border: `1px solid ${t.colors.border}`,
    minWidth: 140,
  },
  dropItem: {
    display: "block",
    width: "100%",
    padding: "12px 14px",
    background: "none",
    border: "none",
    textAlign: "left",
    fontSize: 14,
    cursor: "pointer",
    borderRadius: 8,
    color: t.colors.text,
  },
  dropItemDanger: {
    display: "block",
    width: "100%",
    padding: "12px 14px",
    background: "none",
    border: "none",
    textAlign: "left",
    fontSize: 14,
    cursor: "pointer",
    borderRadius: 8,
    color: t.colors.danger,
  },
  menuDot: {
    background: "none",
    border: "none",
    fontSize: 22,
    cursor: "pointer",
    color: t.colors.textMuted,
    padding: 8,
    zIndex: 10,
    position: "relative",
  },
});

// PropertyDetail styles
export const getPropertyDetailStyles = (t, mode) => ({
  container: {
    padding: "0 0 80px",
    background: t.colors.bg,
    minHeight: "100vh",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px 20px",
    background: mode === "dark" ? "rgba(10,10,10,0.9)" : "rgba(255,255,255,0.9)",
    backdropFilter: "blur(10px)",
    position: "sticky",
    top: 0,
    zIndex: 10,
    borderBottom: `1px solid ${t.colors.border}`,
  },
  backBtn: {
    background: "none",
    border: "none",
    color: t.colors.primary,
    fontWeight: 700,
    fontSize: 15,
    cursor: "pointer",
    padding: 0,
  },
  editBtn: {
    background: t.colors.bgSecondary,
    border: `1px solid ${t.colors.border}`,
    color: t.colors.text,
    borderRadius: 10,
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  iconBtn: {
    background: t.colors.bgSecondary,
    border: `1px solid ${t.colors.border}`,
    color: t.colors.text,
    borderRadius: 10,
    padding: "8px 12px",
    fontSize: 14,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 40,
  },
  heroWrap: {
    position: "relative",
    cursor: "pointer",
  },
  heroImg: {
    width: "100%",
    height: 260,
    objectFit: "cover",
    display: "block",
  },
  heroBadge: {
    position: "absolute",
    bottom: 16,
    right: 16,
    background: "rgba(0,0,0,0.7)",
    backdropFilter: "blur(10px)",
    color: t.colors.text,
    borderRadius: 20,
    padding: "6px 12px",
    fontSize: 12,
    fontWeight: 700,
  },
  card: {
    background: t.colors.bgSecondary,
    borderRadius: 16,
    margin: "16px 20px 0",
    padding: 20,
    boxShadow: mode === "dark" ? "0 4px 20px rgba(0,0,0,0.3)" : "0 2px 8px rgba(0,0,0,0.05)",
    border: `1px solid ${t.colors.border}`,
  },
  name: {
    fontWeight: 800,
    fontSize: 20,
    color: t.colors.text,
    marginBottom: 6,
  },
  sub: {
    fontSize: 14,
    color: t.colors.textMuted,
    marginBottom: 12,
  },
  estadoSelect: {
    fontSize: 11,
    fontWeight: 700,
    borderRadius: 20,
    padding: "4px 10px",
    cursor: "pointer",
    outline: "none",
    background: t.colors.bgSecondary,
    border: `1px solid ${t.colors.border}`,
    color: t.colors.text,
  },
  precioBlock: {
    fontSize: 18,
    fontWeight: 700,
    color: t.colors.primary,
    marginTop: 8,
  },
  mantBlock: {
    fontSize: 13,
    color: t.colors.textMuted,
    marginTop: 6,
  },
  tabRow: {
    display: "flex",
    gap: 10,
    padding: "16px 20px 0",
  },
  tab: {
    flex: 1,
    padding: "10px 0",
    borderRadius: 12,
    border: `1px solid ${t.colors.border}`,
    background: t.colors.bgSecondary,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    color: t.colors.textMuted,
    transition: "all 0.3s ease",
  },
  tabActive: {
    background: "linear-gradient(135deg, #d4af37 0%, #b8962e 100%)",
    color: "#0a0a0a",
    border: "none",
    boxShadow: "0 4px 15px rgba(212,175,55,0.3)",
  },
  msgBox: {
    margin: "12px 20px 0",
    background: t.colors.bgSecondary,
    borderRadius: 16,
    padding: 16,
    border: `1px solid ${t.colors.border}`,
  },
  msgPre: {
    fontFamily: "'Outfit',sans-serif",
    fontSize: 14,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    color: t.colors.textSecondary,
    margin: "0 0 16px",
    lineHeight: 1.7,
  },
  msgPreNoBox: {
    fontFamily: "'Outfit',sans-serif",
    fontSize: 14,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    color: t.colors.textSecondary,
    background: "none",
    border: "none",
    padding: 0,
    margin: "0 0 12px",
    lineHeight: 1.6,
  },
  actionGrid: {
    display: "flex",
    gap: 10,
    padding: "16px 20px 0",
    flexWrap: "wrap",
  },
  actionBtn: {
    flex: "1 1 calc(50% - 5px)",
    padding: "14px 0",
    background: t.colors.bgSecondary,
    border: `1px solid ${t.colors.border}`,
    borderRadius: 12,
    textAlign: "center",
    textDecoration: "none",
    color: t.colors.text,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.3s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  sectionTitle: {
    fontWeight: 700,
    fontSize: 12,
    color: t.colors.textMuted,
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: "1px",
    textAlign: "center",
  },
});

// PropertyFilters styles
export const getPropertyFiltersStyles = (t) => ({
  searchWrap: {
    padding: "16px 20px 0",
    background: t.colors.bg,
    position: "sticky",
    top: 60,
    zIndex: 5,
  },
  searchInputWrap: {
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  searchIcon: {
    position: "absolute",
    left: 14,
    color: t.colors.textMuted,
    pointerEvents: "none",
  },
  searchInput: {
    width: "100%",
    padding: "12px 16px 12px 44px",
    border: `1px solid ${t.colors.border}`,
    borderRadius: 12,
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
    background: t.colors.bgSecondary,
    color: t.colors.text,
    transition: "all 0.3s ease",
  },
  filterRow: {
    display: "flex",
    gap: 10,
    padding: "12px 20px",
    overflowX: "auto",
    background: t.colors.bg,
  },
  filterSelect: {
    padding: "8px 12px",
    borderRadius: 10,
    border: `1px solid ${t.colors.border}`,
    fontSize: 13,
    background: t.colors.bgSecondary,
    color: t.colors.text,
    flexShrink: 0,
    cursor: "pointer",
    outline: "none",
    minWidth: 100,
  },
  count: {
    padding: "4px 20px 8px",
    fontSize: 12,
    color: t.colors.textMuted,
    fontWeight: 600,
    background: t.colors.bg,
  },
});
