// src/styles/componentStyles.js
// Estilos centralizados para componentes de ROCA App
// Cada función recibe `t` (tema) y opcionalmente `mode`

/**
 * Estilos para PropertyCard
 */
export const getPropertyCardStyles = (t) => ({
  card: {
    background: t.colors.bgCard,
    borderRadius: 16,
    border: `1px solid ${t.colors.border}`,
    position: "relative",
    transition: "all 0.2s ease",
    cursor: "pointer",
  },
  cardMain: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    padding: 16,
    gap: 12,
  },
  cardLeft: {
    flex: 1,
    minWidth: 0,
  },
  cardName: {
    fontWeight: 700,
    fontSize: 15,
    color: t.colors.text,
    marginBottom: 4,
  },
  cardSub: {
    fontSize: 12,
    color: t.colors.textMuted,
    marginBottom: 4,
  },
  cardPrice: {
    fontWeight: 700,
    fontSize: 14,
    color: t.colors.primary,
  },
  cardRight: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    position: "relative",
  },
  statusBadge: (ec) => ({
    fontSize: 11,
    fontWeight: 700,
    borderRadius: 20,
    padding: "4px 10px",
    display: "flex",
    alignItems: "center",
    whiteSpace: "nowrap",
    backgroundColor: ec?.bg || t.colors.success,
    color: ec?.text || t.colors.text,
  }),
  statusDot: (ec) => ({
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: ec?.dot || t.colors.text,
    display: "inline-block",
    marginRight: 4,
  }),
  dropdown: {
    background: t.colors.bgCard,
    borderRadius: 12,
    padding: 8,
    boxShadow: "0 8px 32px rgba(0,0,0,0.5)",
    position: "absolute",
    right: "100%",
    marginRight: 8,
    top: "50%",
    transform: "translateY(-50%)",
    zIndex: 50,
    border: `1px solid ${t.colors.border}`,
    minWidth: 140,
  },
  dropItem: {
    display: "block",
    width: "100%",
    padding: "12px 14px",
    background: "none",
    border: "none",
    textAlign: "left",
    fontSize: 14,
    cursor: "pointer",
    borderRadius: 8,
    color: t.colors.text,
  },
  dropItemDanger: {
    display: "block",
    width: "100%",
    padding: "12px 14px",
    background: "none",
    border: "none",
    textAlign: "left",
    fontSize: 14,
    cursor: "pointer",
    borderRadius: 8,
    color: t.colors.danger,
  },
  menuDot: {
    background: "none",
    border: "none",
    fontSize: 22,
    cursor: "pointer",
    color: t.colors.textMuted,
    padding: 8,
    zIndex: 10,
    position: "relative",
  },
});

/**
 * Estilos para PropertyDetail
 */
export const getPropertyDetailStyles = (t, mode) => ({
  container: {
    padding: "0 0 80px",
    background: t.colors.bg,
    minHeight: "100vh",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px 20px",
    background: mode === 'dark' ? "rgba(10,10,10,0.9)" : "rgba(255,255,255,0.9)",
    backdropFilter: "blur(10px)",
    position: "sticky",
    top: 0,
    zIndex: 10,
    borderBottom: `1px solid ${t.colors.border}`,
  },
  backBtn: {
    background: "none",
    border: "none",
    color: t.colors.primary,
    fontWeight: 700,
    fontSize: 15,
    cursor: "pointer",
    padding: 0,
  },
  iconBtn: {
    background: t.colors.bgSecondary,
    border: `1px solid ${t.colors.border}`,
    color: t.colors.text,
    borderRadius: 10,
    padding: "8px 12px",
    fontSize: 14,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 40,
  },
  heroWrap: {
    position: "relative",
    cursor: "pointer",
  },
  heroImg: {
    width: "100%",
    height: 260,
    objectFit: "cover",
    display: "block",
  },
  heroBadge: {
    position: "absolute",
    bottom: 16,
    right: 16,
    background: "rgba(0,0,0,0.7)",
    backdropFilter: "blur(10px)",
    color: "#ffffff",
    borderRadius: 20,
    padding: "6px 12px",
    fontSize: 12,
    fontWeight: 700,
  },
  card: {
    background: t.colors.bgCard,
    borderRadius: 16,
    margin: "16px 20px 0",
    padding: 20,
    boxShadow: mode === 'dark' ? "0 4px 20px rgba(0,0,0,0.3)" : "0 2px 8px rgba(0,0,0,0.05)",
    border: `1px solid ${t.colors.border}`,
  },
  name: {
    fontWeight: 800,
    fontSize: 20,
    color: t.colors.text,
    marginBottom: 6,
  },
  sub: {
    fontSize: 14,
    color: t.colors.textMuted,
    marginBottom: 12,
  },
  estadoSelect: {
    fontSize: 11,
    fontWeight: 700,
    borderRadius: 20,
    padding: "4px 10px",
    cursor: "pointer",
    outline: "none",
    background: t.colors.bgSecondary,
    border: `1px solid ${t.colors.border}`,
    color: t.colors.text,
  },
  precioBlock: {
    fontSize: 18,
    fontWeight: 700,
    color: t.colors.primary,
    marginTop: 8,
  },
  mantBlock: {
    fontSize: 13,
    color: t.colors.textMuted,
    marginTop: 6,
  },
  tabRow: {
    display: "flex",
    gap: 10,
    padding: "16px 20px 0",
  },
  tab: {
    flex: 1,
    padding: "10px 0",
    borderRadius: 12,
    border: `1px solid ${t.colors.border}`,
    background: t.colors.bgSecondary,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    color: t.colors.textMuted,
    transition: "all 0.3s ease",
  },
  tabActive: {
    background: "linear-gradient(135deg, #d4af37 0%, #b8962e 100%)",
    color: "#0a0a0a",
    border: "none",
    boxShadow: "0 4px 15px rgba(212,175,55,0.3)",
  },
  msgBox: {
    margin: "12px 20px 0",
    background: t.colors.bgCard,
    borderRadius: 16,
    padding: 16,
    border: `1px solid ${t.colors.border}`,
  },
  msgPre: {
    fontFamily: "'Outfit',sans-serif",
    fontSize: 14,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    color: t.colors.textSecondary,
    margin: "0 0 16px",
    lineHeight: 1.7,
  },
  msgPreNoBox: {
    fontFamily: "'Outfit',sans-serif",
    fontSize: 14,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    color: t.colors.textSecondary,
    background: "none",
    border: "none",
    padding: 0,
    margin: "0 0 12px",
    lineHeight: 1.6,
  },
  actionGrid: {
    display: "flex",
    gap: 10,
    padding: "16px 20px 0",
    flexWrap: "wrap",
  },
  actionBtn: {
    flex: "1 1 calc(50% - 5px)",
    padding: "14px 0",
    background: t.colors.bgSecondary,
    border: `1px solid ${t.colors.border}`,
    borderRadius: 12,
    textAlign: "center",
    textDecoration: "none",
    color: t.colors.text,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.3s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  sectionTitle: {
    fontWeight: 700,
    fontSize: 12,
    color: t.colors.textMuted,
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: "1px",
    textAlign: "center",
  },
});

/**
 * Estilos para PropertyForm
 */
export const getFormStyles = (theme) => ({
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.8)",
    backdropFilter: "blur(10px)",
    zIndex: 100,
    display: "flex",
    alignItems: "flex-end",
  },
  modal: {
    background: theme.colors.bg,
    borderRadius: 0,
    width: "100%",
    maxHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    marginTop: 0,
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "20px 24px",
    borderBottom: `1px solid ${theme.colors.border}`,
    flexShrink: 0,
  },
  title: {
    fontWeight: 800,
    fontSize: 18,
    color: theme.colors.text,
  },
  closeBtn: {
    background: "none",
    border: "none",
    fontSize: 22,
    cursor: "pointer",
    color: theme.colors.textMuted,
    padding: 4,
  },
  body: {
    overflowY: "auto",
    padding: "20px 24px",
    flex: 1,
  },
  footer: {
    display: "flex",
    gap: 12,
    padding: "16px 24px",
    borderTop: `1px solid ${theme.colors.border}`,
    flexShrink: 0,
  },
  cancelBtn: {
    flex: 1,
    padding: 14,
    background: theme.colors.bgSecondary,
    border: `1px solid ${theme.colors.border}`,
    borderRadius: 12,
    fontWeight: 700,
    fontSize: 15,
    cursor: "pointer",
    color: theme.colors.text,
  },
  saveBtn: {
    flex: 2,
    padding: 14,
    background: "linear-gradient(135deg, #d4af37 0%, #b8962e 100%)",
    color: "#0a0a0a",
    border: "none",
    borderRadius: 12,
    fontWeight: 700,
    fontSize: 15,
    cursor: "pointer",
    boxShadow: "0 4px 15px rgba(212,175,55,0.3)",
  },
  section: {
    fontWeight: 800,
    fontSize: 11,
    color: theme.colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: "1px",
    margin: "20px 0 12px",
    paddingBottom: 8,
    borderBottom: `1px solid ${theme.colors.border}`,
  },
  row2: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
  },
  checkGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
    marginBottom: 14,
  },
  uploadBtn: {
    width: "100%",
    padding: "14px",
    background: theme.colors.bgSecondary,
    border: `1.5px dashed ${theme.colors.border}`,
    borderRadius: 12,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    marginBottom: 14,
    color: theme.colors.text,
    transition: "all 0.3s ease",
  },
  photoGrid: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    marginBottom: 14,
  },
  photoThumbWrap: {
    position: "relative",
    transition: "transform 0.2s ease, border 0.2s ease, background-color 0.2s ease",
    borderRadius: 10,
    overflow: "hidden",
    minWidth: 80,
    minHeight: 80,
  },
  photoThumb: {
    width: 80,
    height: 80,
    objectFit: "cover",
    borderRadius: 10,
    display: "block",
  },
  photoRemove: {
    position: "absolute",
    top: 4,
    right: 4,
    background: "#ef4444",
    color: "#fff",
    border: "none",
    borderRadius: "50%",
    width: 20,
    height: 20,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 2px 4px rgba(0,0,0,0.3)",
  },
  dragHandle: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    fontSize: 18,
    color: "#ffffff",
    background: "rgba(0,0,0,0.7)",
    borderRadius: 8,
    padding: "8px 12px",
    cursor: "grab",
    zIndex: 5,
    letterSpacing: 1,
    pointerEvents: "auto",
    border: "1px solid rgba(255,255,255,0.2)",
  },
  mainPhotoBadge: {
    position: "absolute",
    bottom: 6,
    left: "50%",
    transform: "translateX(-50%)",
    fontSize: 9,
    fontWeight: 700,
    color: "#ffffff",
    background: "linear-gradient(135deg, #d4af37 0%, #b8962e 100%)",
    borderRadius: 4,
    padding: "2px 8px",
    whiteSpace: "nowrap",
  },
  spinner: {
    width: 16,
    height: 16,
    border: "2px solid rgba(255,255,255,0.3)",
    borderTopColor: "#ffffff",
    borderRadius: "50%",
    animation: "spin 0.8s linear infinite",
  },
});

/**
 * Estilos para ClientsView y ClientForm
 */
export const getClientsViewStyles = (t, mode) => {
  const primaryDark = "#0a0a0a";
  const waColor = "#25D366";
  const telColor = "#3b82f6";
  const dangerBg = "rgba(239,68,68,0.1)";
  const dangerBorder = "rgba(239,68,68,0.2)";
  const dangerText = "#ef4444";

  return {
    // Contenedor principal
    container: {
      minHeight: "100vh",
      background: t.colors.bg,
      color: t.colors.text,
      fontFamily: "'Outfit', sans-serif",
      paddingBottom: 80,
    },
    // Header
    header: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      padding: "16px 20px",
      background: mode === "dark" ? "rgba(10,10,10,0.85)" : "rgba(255,255,255,0.85)",
      backdropFilter: "blur(10px)",
      position: "sticky",
      top: 0,
      zIndex: 10,
      borderBottom: `1px solid ${t.colors.border}`,
    },
    backBtn: {
      background: "none",
      border: "none",
      color: t.colors.primary,
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      gap: 6,
      fontSize: 15,
      fontWeight: 700,
    },
    headerTitle: {
      fontWeight: 800,
      fontSize: 17,
      color: t.colors.text,
    },
    addBtn: {
      background: t.colors.primary,
      color: primaryDark,
      border: "none",
      borderRadius: 10,
      padding: "8px 14px",
      fontSize: 13,
      fontWeight: 700,
      cursor: "pointer",
      boxShadow: "0 4px 15px rgba(212,175,55,0.3)",
    },
    // Filtros
    filterContainer: {
      display: "flex",
      gap: 8,
      padding: "12px 20px",
      overflowX: "auto",
    },
    filterBtn: (isActive) => ({
      flexShrink: 0,
      padding: "6px 14px",
      borderRadius: 20,
      border: "none",
      fontSize: 12,
      fontWeight: 700,
      cursor: "pointer",
      background: isActive ? t.colors.primary : t.colors.bgSecondary,
      color: isActive ? primaryDark : t.colors.textMuted,
    }),
    // Contador
    counter: {
      padding: "0 20px 8px",
      fontSize: 12,
      color: t.colors.textMuted,
      fontWeight: 600,
    },
    // Lista
    list: {
      padding: "0 20px",
      display: "flex",
      flexDirection: "column",
      gap: 12,
    },
    empty: {
      textAlign: "center",
      padding: "60px 0",
      color: t.colors.textMuted,
      fontSize: 14,
    },
    // Tarjeta de lead
    leadCard: {
      background: t.colors.bgCard,
      borderRadius: 16,
      border: `1px solid ${t.colors.border}`,
      padding: 16,
    },
    leadRow: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "flex-start",
    },
    leadInfo: {
      flex: 1,
      minWidth: 0,
    },
    leadName: {
      fontWeight: 700,
      fontSize: 15,
      color: t.colors.text,
      marginBottom: 2,
    },
    leadPhone: {
      fontSize: 13,
      color: t.colors.textMuted,
      marginBottom: 4,
    },
    leadProperty: {
      fontSize: 12,
      color: t.colors.textMuted,
      marginBottom: 8,
    },
    leadNote: {
      fontSize: 13,
      color: t.colors.textMuted,
      background: t.colors.bgSecondary,
      borderRadius: 8,
      padding: "6px 10px",
      marginBottom: 8,
    },
    // Select de estado
    estadoSelect: (ec) => ({
      fontSize: 11,
      fontWeight: 700,
      borderRadius: 20,
      padding: "4px 10px",
      cursor: "pointer",
      outline: "none",
      border: "none",
      backgroundColor: ec.bg,
      color: ec.text,
    }),
    // Acciones
    actions: {
      display: "flex",
      flexDirection: "column",
      gap: 8,
      marginLeft: 12,
    },
    actionBtn: {
      background: t.colors.bgSecondary,
      border: `1px solid ${t.colors.border}`,
      color: t.colors.text,
      borderRadius: 10,
      padding: "8px 10px",
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    waBtn: {
      background: waColor,
      color: "#fff",
      border: "none",
      borderRadius: 10,
      padding: "8px 10px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      textDecoration: "none",
    },
    telBtn: {
      background: telColor,
      color: "#fff",
      border: "none",
      borderRadius: 10,
      padding: "8px 10px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      textDecoration: "none",
    },
    deleteBtn: {
      background: dangerBg,
      border: `1px solid ${dangerBorder}`,
      color: dangerText,
      borderRadius: 10,
      padding: "8px 10px",
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    // Formulario modal
    modalOverlay: {
      position: "fixed",
      inset: 0,
      background: "rgba(0,0,0,0.8)",
      backdropFilter: "blur(10px)",
      zIndex: 100,
      display: "flex",
      alignItems: "flex-end",
    },
    modal: {
      background: t.colors.bgSecondary,
      width: "100%",
      maxHeight: "90vh",
      display: "flex",
      flexDirection: "column",
      borderRadius: "20px 20px 0 0",
    },
    modalHeader: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      padding: "20px 24px",
      borderBottom: `1px solid ${t.colors.border}`,
    },
    modalTitle: {
      fontWeight: 800,
      fontSize: 18,
      color: t.colors.text,
    },
    modalBody: {
      overflowY: "auto",
      padding: "20px 24px",
      flex: 1,
      display: "flex",
      flexDirection: "column",
      gap: 14,
    },
    modalFooter: {
      display: "flex",
      gap: 12,
      padding: "16px 24px",
      borderTop: `1px solid ${t.colors.border}`,
    },
    input: {
      width: "100%",
      padding: "12px 14px",
      borderRadius: 12,
      border: `1px solid ${t.colors.border}`,
      fontSize: 15,
      boxSizing: "border-box",
      outline: "none",
      background: "rgba(255,255,255,0.03)",
      color: t.colors.text,
    },
    label: {
      display: "block",
      fontSize: 12,
      fontWeight: 600,
      color: t.colors.textMuted,
      marginBottom: 6,
      textTransform: "uppercase",
      letterSpacing: "0.5px",
    },
    cancelBtn: {
      flex: 1,
      padding: 14,
      background: "rgba(255,255,255,0.08)",
      border: `1px solid ${t.colors.border}`,
      borderRadius: 12,
      fontWeight: 700,
      fontSize: 15,
      cursor: "pointer",
      color: t.colors.text,
    },
    saveBtn: {
      flex: 2,
      padding: 14,
      background: t.colors.primary,
      color: primaryDark,
      border: "none",
      borderRadius: 12,
      fontWeight: 700,
      fontSize: 15,
      cursor: "pointer",
      boxShadow: "0 4px 15px rgba(212,175,55,0.3)",
    },
  };
};

/**
 * Estilos para el menú de perfil (drawer)
 */
export const getProfileMenuStyles = (theme) => ({
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: "rgba(0,0,0,0.5)",
    zIndex: 99,
  },
  drawer: {
    position: "fixed",
    top: 0,
    left: 0,
    width: 280,
    height: "100%",
    background: theme.colors.bgSecondary,
    boxShadow: "4px 0 20px rgba(0,0,0,0.5)",
    zIndex: 100,
    padding: "20px 0",
    display: "flex",
    flexDirection: "column",
  },
  header: {
    padding: "0 20px 20px",
    borderBottom: `1px solid ${theme.colors.border}`,
    marginBottom: 20,
  },
  userInfo: {
    color: theme.colors.text,
    fontSize: 16,
    fontWeight: 600,
    marginBottom: 4,
  },
  userEmail: {
    color: theme.colors.textMuted,
    fontSize: 12,
  },
  closeBtn: {
    position: "absolute",
    top: 16,
    right: 16,
    background: "none",
    border: "none",
    color: theme.colors.text,
    fontSize: 24,
    cursor: "pointer",
  },
  item: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    width: "100%",
    padding: "14px 20px",
    background: "none",
    border: "none",
    color: theme.colors.text,
    fontSize: 15,
    cursor: "pointer",
    textAlign: "left",
  },
  divider: {
    height: 1,
    background: theme.colors.border,
    margin: "12px 0",
  },
});

/**
 * Estilos para la aplicación principal (S dinámico en App.jsx)
 */
export const getAppStyles = (theme, mode) => ({
  app: {
    minHeight: "100vh",
    background: theme.colors.bg,
    fontFamily: "'Outfit', sans-serif",
    paddingBottom: 80,
    color: theme.colors.text,
  },
  authWrap: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: mode === "dark"
      ? "linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 50%, #0a0a0a 100%)"
      : "linear-gradient(135deg, #f5f5f5 0%, #e0e0e0 50%, #f5f5f5 100%)",
  },
  authCard: {
    background: theme.colors.bgSecondary,
    backdropFilter: "blur(20px)",
    border: `1px solid ${theme.colors.border}`,
    padding: 40,
    borderRadius: 24,
    width: "90%",
    maxWidth: 360,
    textAlign: "center",
    boxShadow: mode === "dark"
      ? "0 8px 32px rgba(0,0,0,0.4), 0 0 60px rgba(212,175,55,0.08)"
      : "0 8px 32px rgba(0,0,0,0.1)",
  },
  input: {
    width: "100%",
    padding: "14px 16px",
    border: `1px solid ${theme.colors.border}`,
    borderRadius: 12,
    fontSize: 15,
    outline: "none",
    boxSizing: "border-box",
    background: theme.colors.bgSecondary,
    color: theme.colors.text,
    transition: "all 0.3s ease",
  },
  newBtn: {
    background: "linear-gradient(135deg, #d4af37 0%, #b8962e 100%)",
    color: "#0a0a0a",
    border: "none",
    borderRadius: 10,
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 4px 15px rgba(212,175,55,0.3)",
  },
  topBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px 20px",
    background: mode === "dark" ? "rgba(10,10,10,0.85)" : "rgba(255,255,255,0.85)",
    backdropFilter: "blur(10px)",
    position: "sticky",
    top: 0,
    zIndex: 10,
    borderBottom: `1px solid ${theme.colors.border}`,
  },
  logo: {
    fontWeight: 800,
    fontSize: 20,
    color: "#d4af37",
    letterSpacing: "1px",
  },
  userTag: {
    color: theme.colors.textMuted,
    fontSize: 12,
    marginRight: 10,
    fontWeight: 500,
  },
  list: {
    background: theme.colors.bg,
    padding: "16px 20px 100px",
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  empty: {
    textAlign: "center",
    padding: "60px 0",
    color: theme.colors.textMuted,
    fontSize: 14,
  },
  loadingWrap: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    background: theme.colors.bg,
    color: theme.colors.textMuted,
  },
  // Propiedades para filtros (las usa PropertyFilters)
  searchWrap: {
    padding: "16px 20px 0",
    background: theme.colors.bg,
    position: "sticky",
    top: 60,
    zIndex: 5,
  },
  searchInput: {
    width: "100%",
    padding: "12px 16px",
    border: `1px solid ${theme.colors.border}`,
    borderRadius: 12,
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
    background: theme.colors.bgSecondary,
    color: theme.colors.text,
  },
  filterRow: {
    display: "flex",
    gap: 8,
    padding: "10px 20px",
    background: theme.colors.bg,
  },
  filterSelect: {
    flex: 1,
    padding: "8px 8px",
    border: `1px solid ${theme.colors.border}`,
    borderRadius: 10,
    fontSize: 11,
    background: theme.colors.bgSecondary,
    cursor: "pointer",
    whiteSpace: "nowrap",
    color: theme.colors.text,
    minWidth: 0,
  },
  count: {
    padding: "8px 20px",
    fontSize: 12,
    color: theme.colors.textMuted,
    fontWeight: 600,
    background: theme.colors.bg,
  },
  // Sign out button (App.jsx)
  signOutBtn: {
    background: theme.colors.bgSecondary,
    border: `1px solid ${theme.colors.border}`,
    borderRadius: 10,
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    color: theme.colors.text,
  },
  // Card styles (PropertyCard in App.jsx - duplicados para App.jsx específicamente)
  card: {
    background: theme.colors.bgCard,
    borderRadius: 16,
    marginBottom: 12,
    boxShadow: mode === "dark" ? "0 4px 20px rgba(0,0,0,0.3)" : "0 4px 20px rgba(0,0,0,0.08)",
    border: `1px solid ${theme.colors.border}`,
    transition: "all 0.3s ease",
  },
  cardMain: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    padding: 16,
  },
  cardLeft: { flex: 1 },
  cardName: {
    fontWeight: 700,
    fontSize: 16,
    color: theme.colors.text,
    marginBottom: 4,
  },
  cardSub: {
    fontSize: 13,
    color: theme.colors.textMuted,
    marginBottom: 8,
  },
  cardPrice: {
    fontSize: 14,
    fontWeight: 700,
    color: theme.colors.primary,
  },
  cardRight: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    position: "relative",
  },
  menuDot: {
    background: "none",
    border: "none",
    fontSize: 22,
    cursor: "pointer",
    color: theme.colors.textMuted,
    padding: 8,
    zIndex: 10,
    position: "relative",
  },
  dropdown: {
    background: theme.colors.bgCard,
    borderRadius: 12,
    padding: 8,
    boxShadow: "0 8px 32px rgba(0,0,0,0.5)",
    position: "absolute",
    right: "100%",
    marginRight: 8,
    top: "50%",
    transform: "translateY(-50%)",
    zIndex: 50,
    border: `1px solid ${theme.colors.border}`,
    minWidth: 140,
  },
  dropItem: {
    display: "block",
    width: "100%",
    padding: "12px 14px",
    background: "none",
    border: "none",
    textAlign: "left",
    fontSize: 14,
    cursor: "pointer",
    borderRadius: 8,
    color: theme.colors.text,
  },
  dropDivider: {
    height: 1,
    background: theme.colors.border,
    margin: "8px 0",
  },
});